AWSTemplateFormatVersion: '2010-09-09'
Description: Memoru LIFF - CloudFront + S3 Static Hosting

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  DomainName:
    Type: String
    Default: ''
    Description: Custom domain name for LIFF app (leave empty to use CloudFront domain)

  HostedZoneId:
    Type: String
    Default: ''
    Description: Route53 Hosted Zone ID (required if DomainName is set)

  CertificateArn:
    Type: String
    Default: ''
    Description: ACM Certificate ARN in us-east-1 (required if DomainName is set)

  ApiEndpoint:
    Type: String
    Default: ''
    Description: Backend API Gateway endpoint URL

Conditions:
  HasCustomDomain: !Not [!Equals [!Ref DomainName, '']]
  HasCertificate: !Not [!Equals [!Ref CertificateArn, '']]
  HasHostedZone: !Not [!Equals [!Ref HostedZoneId, '']]
  IsProd: !Equals [!Ref Environment, prod]

Resources:
  #============================================================
  # S3 Bucket for Static Files
  #============================================================
  LiffBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub memoru-liff-${Environment}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
          - Id: AbortIncompleteMultipartUpload
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - !If
                - HasCustomDomain
                - !Sub https://${DomainName}
                - '*'
            MaxAge: 3600
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: memoru

  # S3 Bucket Policy for CloudFront OAC
  LiffBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LiffBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${LiffBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${LiffDistribution}

  #============================================================
  # CloudFront Distribution
  #============================================================

  # Origin Access Control
  LiffOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub memoru-liff-oac-${Environment}
        Description: OAC for Memoru LIFF S3 bucket
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # Cache Policy for static assets
  StaticAssetsCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub memoru-liff-static-${Environment}
        DefaultTTL: 86400
        MaxTTL: 31536000
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true

  # Response Headers Policy
  SecurityHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub memoru-liff-security-headers-${Environment}
        SecurityHeadersConfig:
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Override: true
            Preload: true
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          XSSProtection:
            ModeBlock: true
            Override: true
            Protection: true
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: true
          ContentSecurityPolicy:
            ContentSecurityPolicy: !Sub >-
              default-src 'self';
              script-src 'self' 'unsafe-inline' https://static.line-scdn.net;
              style-src 'self' 'unsafe-inline';
              img-src 'self' data: https: blob:;
              font-src 'self' data:;
              connect-src 'self' ${ApiEndpoint} https://api.line.me https://access.line.me;
              frame-ancestors 'self' https://liff.line.me;
            Override: true

  # CloudFront Distribution
  LiffDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub Memoru LIFF Distribution - ${Environment}
        DefaultRootObject: index.html
        HttpVersion: http2and3
        IPV6Enabled: true
        PriceClass: PriceClass_200
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt LiffBucket.RegionalDomainName
            OriginAccessControlId: !Ref LiffOAC
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
          ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy
          Compress: true
        CacheBehaviors:
          # Long-term cache for static assets (JS, CSS, images with hash)
          - PathPattern: /assets/*
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: !Ref StaticAssetsCachePolicy
            ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy
            Compress: true
          # No cache for index.html
          - PathPattern: /index.html
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled
            ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy
            Compress: true
        CustomErrorResponses:
          # SPA routing support - redirect 403/404 to index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
        Aliases: !If
          - HasCustomDomain
          - - !Ref DomainName
          - !Ref AWS::NoValue
        ViewerCertificate: !If
          - HasCertificate
          - AcmCertificateArn: !Ref CertificateArn
            MinimumProtocolVersion: TLSv1.2_2021
            SslSupportMethod: sni-only
          - CloudFrontDefaultCertificate: true
        Logging: !If
          - IsProd
          - Bucket: !GetAtt LogBucket.DomainName
            Prefix: cloudfront/
            IncludeCookies: false
          - !Ref AWS::NoValue
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: memoru

  # Log Bucket (for production)
  LogBucket:
    Type: AWS::S3::Bucket
    Condition: IsProd
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub memoru-logs-${Environment}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 90
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: memoru

  #============================================================
  # Route53 DNS Record (Optional)
  #============================================================
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasHostedZone
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt LiffDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront Hosted Zone ID (fixed)
        EvaluateTargetHealth: false

Outputs:
  BucketName:
    Description: S3 Bucket name for LIFF app
    Value: !Ref LiffBucket
    Export:
      Name: !Sub memoru-${Environment}-liff-bucket

  BucketArn:
    Description: S3 Bucket ARN
    Value: !GetAtt LiffBucket.Arn
    Export:
      Name: !Sub memoru-${Environment}-liff-bucket-arn

  DistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref LiffDistribution
    Export:
      Name: !Sub memoru-${Environment}-liff-distribution-id

  DistributionDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt LiffDistribution.DomainName
    Export:
      Name: !Sub memoru-${Environment}-liff-distribution-domain

  LiffUrl:
    Description: LIFF Application URL
    Value: !If
      - HasCustomDomain
      - !Sub https://${DomainName}
      - !Sub https://${LiffDistribution.DomainName}
    Export:
      Name: !Sub memoru-${Environment}-liff-url

  DeployCommand:
    Description: Command to deploy LIFF app
    Value: !Sub |
      aws s3 sync ./dist s3://${LiffBucket} --delete && \
      aws cloudfront create-invalidation --distribution-id ${LiffDistribution} --paths "/*"
